package Models;

public class Rating {
    private int ratingId;  // auto-generated by database
    private User fromUser; // The person giving the rating
    private User toUser;   // The vendor or NGO being rated
    private int score;     // 1 to 5 stars
    private String comment;

    // Default Constructor: Required for some DAO mapping and JavaFX operations
    public Rating() {}

    // Constructor without ratingId (for new ratings)
    public Rating(User fromUser, User toUser, int score, String comment) {
        this.fromUser = fromUser;
        this.toUser = toUser;
        this.score = score;
        this.comment = comment;
    }

    // Constructor with ratingId (for retrieving from database)
    public Rating(int ratingId, User fromUser, User toUser, int score, String comment) {
        this.ratingId = ratingId;
        this.fromUser = fromUser;
        this.toUser = toUser;
        this.score = score;
        this.comment = comment;
    }

    // Getters and Setters
    public int getRatingId() { return ratingId; }
    public void setRatingId(int ratingId) { this.ratingId = ratingId; }

    public User getFromUser() { return fromUser; }
    public void setFromUser(User fromUser) { this.fromUser = fromUser; }

    public User getToUser() { return toUser; }
    public void setToUser(User toUser) { this.toUser = toUser; }

    public int getScore() { return score; }
    public void setScore(int score) { this.score = score; }

    public String getComment() { return comment; }
    public void setComment(String comment) { this.comment = comment; }

    @Override
    public String toString() {
        return "Rating from " + fromUser.getName() + ": " + score + "/5 - " + comment;
    }
}
