package Models;

import java.time.LocalDateTime;
public class Transaction {
    private int transactionId; // Auto-generated by database
    private User buyer;        // The User or NGO making the purchase
    private Vendor vendor;     // The Restaurant or Vendor providing the food
    private String foodItem;   // Name of the surplus food item
    private double amount;     // Transaction price
    private LocalDateTime transactionTime;
    private String status;     // "PENDING", "COMPLETED", "EXPIRED"

    // Constructor A: For creating NEW transactions (No ID needed yet)
    public Transaction(User buyer, Vendor vendor, String foodItem, double amount) {
        this.buyer = buyer;
        this.vendor = vendor;
        this.foodItem = foodItem;
        this.amount = amount;
        this.transactionTime = LocalDateTime.now(); // Automatically record current time
        this.status = "COMPLETED"; // Default for First-Come-First-Serve logic
    }

    // Constructor B: For retrieving EXISTING transactions from database (Includes ID)
    public Transaction(int transactionId, User buyer, Vendor vendor, String foodItem, double amount, LocalDateTime time, String status) {
        this.transactionId = transactionId;
        this.buyer = buyer;
        this.vendor = vendor;
        this.foodItem = foodItem;
        this.amount = amount;
        this.transactionTime = time;
        this.status = status;
    }

    // --- Getters and Setters ---

    public int getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(int transactionId) {
        this.transactionId = transactionId;
    }

    public User getBuyer() {
        return buyer;
    }

    public void setBuyer(User buyer) {
        this.buyer = buyer;
    }

    public Vendor getVendor() {
        return vendor;
    }

    public void setVendor(Vendor vendor) {
        this.vendor = vendor;
    }

    public String getFoodItem() {
        return foodItem;
    }

    public void setFoodItem(String foodItem) {
        this.foodItem = foodItem;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public LocalDateTime getTransactionTime() {
        return transactionTime;
    }

    public void setTransactionTime(LocalDateTime transactionTime) {
        this.transactionTime = transactionTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
